### ISSUE TITLE
Logback configuration fails to connect to Elastic-Stack

### ISSUE THREAD

**Issue by pranav-patil** [pranav-patil/spring-microservices#1]
The spring property logstash.host is not loaded during the loading of logback configuration throwing below exception. The spring property `logstash.host` is present in `discovery-service.yml`, which can be read by `@Value` annotation but not during logback load phase.

`<springProperty scope="context" name="logstashHost" source="logstash.host"/>`

```
|-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[logstash] - Log destination logstashHost_IS_UNDEFINED:5043: connection failed. Waiting 4999ms before attempting reconnection. java.net.SocketTimeoutException: connect timed out
	at java.net.SocketTimeoutException: connect timed out
	at 	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at 	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
```

**Comment by pranav-patil** [comment]
This issue was caused as `logstash.host` property was defined in application.yml loaded from config server is unavailable during logback initialization. As mentioned in [Spring Cloud Issue #477](https://github.com/spring-cloud/spring-cloud-config/issues/477) since we are using logback-spring.xml, we need to define all the properties needed by logback in bootstrap.yml which is initialized earlier to logback. The application.yml configuration from spring config server is initialized after logback initialization. The fix is made as part of commit 0b4e684bc9ad415935bf514e467a26cb3d7d9306.
